version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

workflows:
  build-test:
    jobs:
      - build
      - test:
         context: SNYK_TOKEN

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install -q
  test:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - run:
        command: | 
          sudo npm install -g snyk
          sudo snyk auth $SNYK_TOKEN
          sudo snyk code test