version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install -q
  snyk_code_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - run:
        command: | 
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk code test
  snyk_oss_test:
    docker:
    - image: circleci/node:4.8.2
    steps:
    - checkout
    - snyk/scan:
        token-variable: SNYK_TOKEN
  snyk_container_test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk container test jiajunngjj/docker-goof --file=./Dockerfile
workflows:
  build_and_test:
    jobs:
      - build
      - snyk_code_test:
          requires:
            - build
      - snyk_oss_test:
          requires:
            - build
      - snyk_container_test:
          requires:
            - snyk_code_test
            - snyk_oss_test