version: 2.1

orbs:
  snyk: snyk/snyk@1.0.1

  jobs:
    build:
      docker:
        - image: circleci/node:4.8.2
      steps:
        - checkout
        - run: npm install -q
    test:
      docker:
        - image: circleci/node:4.8.2
      steps:
        - checkout
        - command: | 
            npm install -g snyk
            snyk auth $SNYK_TOKEN
            snyk code test
  workflows:
    build_and_test:
      jobs:
        - build
        - test
