version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install -q
  test:
    docker:
    - image: snyk/snyk-cli:npm
    steps:
    - checkout
    - run:
        command: | 
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk code test
workflows: null